// @ts-ignore
import styles from "../../styles/find.module.css";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import ProductList1 from "../../component/ProductList-type1";
import Explore_SectionTitle from "../../component/Explore_SectionTitle";

function Find() {
  const {
    query: { categories },
  } = useRouter();

  const [tempState, setTempState] = useState('find');

  return (
    <div className="big-container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Discover goods in gabon</title>
      </Head>

      <div className="container">
        <Explore_SectionTitle categories={categories}/>
      </div>
      <button style={ {border: '1px solid var(--accent-color)'} } onClick={()=>{
        setTempState(prevState => prevState == 'find'? "": 'find')
      }}>Click me</button>
      <ProductList1 location={tempState}/>

    </div>
  );
}

export default Find;
