// @ts-ignore
import styles from "../../styles/find.module.css";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import ActiveFilter from "../../component/ActiveFilters";
import FilterOverlay from "../../component/FilterOverlay";
import ProductListGrid from "../../component/ProductList-grid";
import Explore_SectionTitle from "../../component/Explore_SectionTitle";
import Filter from "../../component/ActiveFilters/Filter";
import FindContext from "./FindContext";

function Find() {
  const {
    query: { categories },
  } = useRouter();

  const [displayType, setDisplayType] = useState('single' || 'double');

  return (
    <div className="big-container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Discover goods in gabon</title>
      </Head>
      <FindContext>
        <div className="container">
          <Explore_SectionTitle
            categories={
              Array.isArray(categories)
                ? categories
                : categories
                ? [categories]
                : categories
            }
          />
        </div>

        <FilterOverlay />
        <ActiveFilter displayType={displayType}  setDisplayType={setDisplayType} />

        <main
          className="container"
        >
          <ProductListGrid displayType={displayType} />
        </main>
      </FindContext>
    </div>
  );
}

export default Find;
