// @ts-ignore
import styles from "../../styles/find.module.css";
import Head from "next/head";
import React, { useEffect } from "react";
import { useRouter } from "next/router";
import ProductList1 from "../../component/ProductList-type1";
import Explore_SectionTitle from "../../component/Explore_SectionTitle";

function Find() {
  const {
    query: { categories },
  } = useRouter();

  return (
    <div className="big-container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Discover goods in gabon</title>
      </Head>

      <div className="container">
        <Explore_SectionTitle categories={categories}/>
      </div>
      <ProductList1 />
    </div>
  );
}

export default Find;
