import axios from "axios";
import Link from "next/link";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/LandingPage.module.css";
import ProductListGrid from "../component/ProductList-grid";
import ProductListFlex from "../component/ProductList-flex";

const REPRESENTATIONS = [
  "women",
  "men",
  "pant",
  "women men",
  "utilities",
  "women love",
  "spoons",
  "ustensils",
];




const getUrl = (array) => {
  const query = array.map((element) => `representation=${element}`);
  return query.join("&");
};

type responseData = {
  more: boolean;
  products: [];
  error: [];
};

export default function Home() {
  console.log(process.env)
  const [discoverData, setDiscoverData] = useState(
    Array.from({ length: 10 }).map((e) => ({ representation: "nothing" }))
  );
  const [gridData, setGridData] = useState(
    Array.from({ length: 10 }).map((e) => ({ price: 100 }))
  );

  useEffect(() => {
    (async () => {
      // @ts-ignore
      const [response1, response2] = await Promise.all([
        await axios
          .get(
            `/api/product/representation?${getUrl(
              REPRESENTATIONS
            )}&field=pr_image_url&field=description&field=productName&field=representation`
          )
          .catch((err) => console.log(err)),

        await axios
          .get(
            `/api/product?representation=hot deals`
          )
          .catch((err) => console.log(err)),
      ]);

      let _discoverData: responseData = {
          products: [],
          error: [],
          more: false,
        },
        _gridData: responseData = {
          products: [],
          error: [],
          more: false,
        };

      if (response1) {
        _discoverData = response1.data;
      }
      if (response2) {
        _gridData = response2.data;
      }
      setGridData(_gridData.products);

      setDiscoverData(_discoverData.products);
    })();
  }, []);

  return (
    <div
      className={`${styles.landingPage} big-container`}
      style={{ fontSize: "0.8em" }}
    >
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>buy goods in Gabons</title>
      </Head>

      <div className={styles.imageContainer}>
        <div className={styles.landingImages}>
          <picture>
            <source
              media="(min-width: 700px)"
              srcSet="https://res.cloudinary.com/dkoatnxem/image/upload/ar_2,c_crop/c_scale,w_1000/v1630634875/chris-ainsworth-tIUXSj2iFVY-unsplash_qvqtwi.jpg"
            />
            <source
              media="(min-width: 470px)"
              srcSet="https://res.cloudinary.com/dkoatnxem/image/upload/ar_1.4,c_crop/c_scale,w_300/v1630368802/content-pixie-ZB4eQcNqVUs-unsplash_xdlyul.jpg 600w"
            />
            <source srcSet="https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1400&q=80 600w" />
            <img src="https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1400&q=80" alt="" />
          </picture>
        </div>
        <button>
          <Link href={"/find?categories=women"}>
            <a>Shop Women</a>
          </Link>
        </button>
        <button>
          <Link href={"/find?categories=men"}>
            <a>Shop Men</a>
          </Link>
        </button>
        <button>
          <Link href={"/find?categories=kids"}>
            <a>Shop Kid</a>
          </Link>
        </button>
      </div>

      <div className={styles.discover}>
        <h3>Our Products</h3>
        <ProductListFlex items={discoverData}  />
      </div>

      <div className={styles.proposition}>
        <h3>HOT DEALS</h3>
        <ProductListGrid displayType="single" aspect_ratio={120} items={gridData}  />
      </div>
    </div>
  );
}
