import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="big-container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eget
        pellentesque tellus. Etiam maximus scelerisque diam. Pellentesque eget
        tortor eu turpis euismod ultricies posuere non lorem. Donec mollis
        libero quis placerat cursus. Praesent et lacinia leo, sed malesuada
        libero. Praesent sagittis sed dolor ut mattis. Aenean suscipit velit
        quis lectus semper laoreet. Vivamus quis tristique justo. Mauris
        tincidunt metus eros, eget commodo nisl laoreet eu. Duis quis neque
        odio. Cras leo felis, tempus non ornare in, porta a diam. Fusce vitae
        ultrices.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eget
        pellentesque tellus. Etiam maximus scelerisque diam. Pellentesque eget
        tortor eu turpis euismod ultricies posuere non lorem. Donec mollis
        libero quis placerat cursus. Praesent et lacinia leo, sed malesuada
        libero. Praesent sagittis sed dolor ut mattis. Aenean suscipit velit
        quis lectus semper laoreet. Vivamus quis tristique justo. Mauris
        tincidunt metus eros, eget commodo nisl laoreet eu. Duis quis neque
        odio. Cras leo felis, tempus non ornare in, porta a diam. Fusce vitae
        ultrices.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eget
        pellentesque tellus. Etiam maximus scelerisque diam. Pellentesque eget
        tortor eu turpis euismod ultricies posuere non lorem. Donec mollis
        libero quis placerat cursus. Praesent et lacinia leo, sed malesuada
        libero. Praesent sagittis sed dolor ut mattis. Aenean suscipit velit
        quis lectus semper laoreet. Vivamus quis tristique justo. Mauris
        tincidunt metus eros, eget commodo nisl laoreet eu. Duis quis neque
        odio. Cras leo felis, tempus non ornare in, porta a diam. Fusce vitae
        ultrices.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eget
        pellentesque tellus. Etiam maximus scelerisque diam. Pellentesque eget
        tortor eu turpis euismod ultricies posuere non lorem. Donec mollis
        libero quis placerat cursus. Praesent et lacinia leo, sed malesuada
        libero. Praesent sagittis sed dolor ut mattis. Aenean suscipit velit
        quis lectus semper laoreet. Vivamus quis tristique justo. Mauris
        tincidunt metus eros, eget commodo nisl laoreet eu. Duis quis neque
        odio. Cras leo felis, tempus non ornare in, porta a diam. Fusce vitae
        ultrices.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eget
        pellentesque tellus. Etiam maximus scelerisque diam. Pellentesque eget
        tortor eu turpis euismod ultricies posuere non lorem. Donec mollis
        libero quis placerat cursus. Praesent et lacinia leo, sed malesuada
        libero. Praesent sagittis sed dolor ut mattis. Aenean suscipit velit
        quis lectus semper laoreet. Vivamus quis tristique justo. Mauris
        tincidunt metus eros, eget commodo nisl laoreet eu. Duis quis neque
        odio. Cras leo felis, tempus non ornare in, porta a diam. Fusce vitae
        ultrices.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eget
        pellentesque tellus. Etiam maximus scelerisque diam. Pellentesque eget
        tortor eu turpis euismod ultricies posuere non lorem. Donec mollis
        libero quis placerat cursus. Praesent et lacinia leo, sed malesuada
        libero. Praesent sagittis sed dolor ut mattis. Aenean suscipit velit
        quis lectus semper laoreet. Vivamus quis tristique justo. Mauris
        tincidunt metus eros, eget commodo nisl laoreet eu. Duis quis neque
        odio. Cras leo felis, tempus non ornare in, porta a diam. Fusce vitae
        ultrices.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eget
        pellentesque tellus. Etiam maximus scelerisque diam. Pellentesque eget
        tortor eu turpis euismod ultricies posuere non lorem. Donec mollis
        libero quis placerat cursus. Praesent et lacinia leo, sed malesuada
        libero. Praesent sagittis sed dolor ut mattis. Aenean suscipit velit
        quis lectus semper laoreet. Vivamus quis tristique justo. Mauris
        tincidunt metus eros, eget commodo nisl laoreet eu. Duis quis neque
        odio. Cras leo felis, tempus non ornare in, porta a diam. Fusce vitae
        ultrices.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eget
        pellentesque tellus. Etiam maximus scelerisque diam. Pellentesque eget
        tortor eu turpis euismod ultricies posuere non lorem. Donec mollis
        libero quis placerat cursus. Praesent et lacinia leo, sed malesuada
        libero. Praesent sagittis sed dolor ut mattis. Aenean suscipit velit
        quis lectus semper laoreet. Vivamus quis tristique justo. Mauris
        tincidunt metus eros, eget commodo nisl laoreet eu. Duis quis neque
        odio. Cras leo felis, tempus non ornare in, porta a diam. Fusce vitae
        ultrices.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eget
        pellentesque tellus. Etiam maximus scelerisque diam. Pellentesque eget
        tortor eu turpis euismod ultricies posuere non lorem. Donec mollis
        libero quis placerat cursus. Praesent et lacinia leo, sed malesuada
        libero. Praesent sagittis sed dolor ut mattis. Aenean suscipit velit
        quis lectus semper laoreet. Vivamus quis tristique justo. Mauris
        tincidunt metus eros, eget commodo nisl laoreet eu. Duis quis neque
        odio. Cras leo felis, tempus non ornare in, porta a diam. Fusce vitae
        ultrices.~
    </div>
  );
}
