import Head from "next/head";
import styles from "../styles/LandingPage.module.css";
import MyImage from "../component/MyImage";
import { useScreenSize } from "../shared/CustomHooks";
import ProductListGrid from "../component/ProductList-grid";
import ProductListFlex from "../component/ProductList-flex";

export default function Home() {
  const screenSize = useScreenSize();
  console.log(screenSize);

  return (
    <div className={`${styles.landingPage} big-container`}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>buy goods in Gabons</title>
      </Head>
      
      <div className={styles.imageContainer}>
        <div className={styles.landingImages}>
          <MyImage imageLink={"500x650"} ASPECT_RATIO={130} />
          <MyImage imageLink={"1000x500"} ASPECT_RATIO={50} />
          <MyImage imageLink={"1000x400"} ASPECT_RATIO={40} />
        </div>
        <button>Shop Women</button>
        <button>Shop Men</button>
        <button>Shop Kid</button>
      </div>

      <div className={styles.discover} >
        <h3>Our Products</h3>
        <ProductListFlex />
      </div>

      <div className={styles.proposition}>
        <h3>Discover our Lorem</h3>
        <ProductListGrid displayType="single" />
      </div>
    </div>
  );
}
