import Head from "next/head";
import styles from "../styles/LandingPage.module.css";
import MyImage from "../component/MyImage";

export default function Home() {

  return (
    <div className={`${styles.landingPage} big-container`}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>buy goods in Gabons</title>
      </Head>
          <MyImage imageLink={"500x650"} ASPECT_RATIO={130} />
    </div>
  );
}
